[package]
name = "airbyte-protocol"
version = "0.1.0"
edition = "2021"

description = "Unofficial implementation of the Airbyte protocol"

license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
